development:
  adapter: postgresql
  encoding: unicode
  database: bettracker_dev
  username: ryan
  password: qwerty1234
  host: localhost
  pool: 5

assets:
  adapter: postgresql
  encoding: unicode
  database: bettracker_dev
  username: ryan
  password: qwerty1234
  host: localhost
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: bettracker_test
  username: ryan
  password: qwerty1234
  pool: 5
  host: localhost
  min_messages: WARNING

production:
  adapter: postgresql
  encoding: unicode
  database: bettracker_prod
  host: localhost
  username: ryan
  password: qwerty1234
  pool: 5
